### View results of aggregate test

In [2]:
import pandas as pd

In [ ]:
#Change insert resume test id (csv name)
df = pd.read_csv('aggregate_test_results.csv')

In [4]:
df.head(10)

,Unnamed: 0,tfidf_job_index,tfidf_job_descriptions,tfidf_scores,keyword_matching_job_index,keyword_matching_job_descriptions,keyword_matching_scores,encoder_job_index,encoder_job_descriptions,encoder_scores
0,0,1401,Job Title\n\nSoftware Applications Developer I...,0.603039,0,We are looking for hire experts flutter develo...,5,1305,main responsibility hr administrator mainly ad...,[0.49065423]
1,1,267,The Team\n\nThe IT Consumer group is accountab...,0.597568,1521,Company Description\n\nGuestTek™ is a global l...,5,517,resident administrator responsible administrat...,[0.4840711]
2,2,2057,Company Description\nPositioned at Publicis Gr...,0.588522,1515,JD for Software Engineer\nLocation-Hinjawadi P...,5,2225,qualification required qualification high scho...,[0.47433412]
3,3,431,17791 DevOps Engineer II (Open)\n\nPosition Ty...,0.585314,1516,The project duration is 15 days\nBudget - 10k\...,5,2069,graduation bachelor ’ degree accredited colleg...,[0.46638045]
4,4,1473,"Company Profile\nAt Morgan Stanley, we advise,...",0.583305,1517,Job Description*\nWe are looking for a PHP Dev...,5,2041,position summary art science seeking dynamic d...,[0.46185827]
5,5,949,Company Summary\nIf you share a true passion f...,0.582045,1518,Greeting to All :\nWe are an IT Company Based ...,5,1205,project coordinator san jose/evergreen communi...,[0.45047]
6,6,509,"Responsible for design, development and implem...",0.582037,1519,Qualification\n\nEducation Specialisation Deta...,5,1454,office administrator global local total nation...,[0.45012635]
7,7,1991,Description\n\nPrimary Responsibilities\n\nDes...,0.581794,1520,Yo Corp. is a data communications and security...,5,213,job code 403033 staff assistant iii duty & res...,[0.44600058]
8,8,13,As a member of our Software Engineering Group ...,0.578276,1522,"Roles & Responsibilities:\nWrite clean, mainta...",5,335,administrative secretary position number 99383...,[0.44148213]
9,9,1790,Software Developer - Web\n2200 S. Lakeside Dri...,0.567747,1513,Node JS Location: Chennai (Greams Road) Skills...,5,1394,Basic Qualifications :\n\nBachelor's degree in...,[0.43823946]

In [9]:
tfidf = df.iloc[:,1:4]
tfidf

,tfidf_job_index,tfidf_job_descriptions,tfidf_scores
0,1401,Job Title\n\nSoftware Applications Developer I...,0.603039
1,267,The Team\n\nThe IT Consumer group is accountab...,0.597568
2,2057,Company Description\nPositioned at Publicis Gr...,0.588522
3,431,17791 DevOps Engineer II (Open)\n\nPosition Ty...,0.585314
4,1473,"Company Profile\nAt Morgan Stanley, we advise,...",0.583305
5,949,Company Summary\nIf you share a true passion f...,0.582045
6,509,"Responsible for design, development and implem...",0.582037
7,1991,Description\n\nPrimary Responsibilities\n\nDes...,0.581794
8,13,As a member of our Software Engineering Group ...,0.578276
9,1790,Software Developer - Web\n2200 S. Lakeside Dri...,0.567747

In [11]:
key_words = df.iloc[:,4:7]
key_words

,keyword_matching_job_index,keyword_matching_job_descriptions,keyword_matching_scores
0,0,We are looking for hire experts flutter develo...,5
1,1521,Company Description\n\nGuestTek™ is a global l...,5
2,1515,JD for Software Engineer\nLocation-Hinjawadi P...,5
3,1516,The project duration is 15 days\nBudget - 10k\...,5
4,1517,Job Description*\nWe are looking for a PHP Dev...,5
5,1518,Greeting to All :\nWe are an IT Company Based ...,5
6,1519,Qualification\n\nEducation Specialisation Deta...,5
7,1520,Yo Corp. is a data communications and security...,5
8,1522,"Roles & Responsibilities:\nWrite clean, mainta...",5
9,1513,Node JS Location: Chennai (Greams Road) Skills...,5

In [ ]:
key_words.loc['keyword_matching_job_descriptions']

In [12]:
encoder = df.iloc[:,7:10]
encoder

,encoder_job_index,encoder_job_descriptions,encoder_scores
0,1305,main responsibility hr administrator mainly ad...,[0.49065423]
1,517,resident administrator responsible administrat...,[0.4840711]
2,2225,qualification required qualification high scho...,[0.47433412]
3,2069,graduation bachelor ’ degree accredited colleg...,[0.46638045]
4,2041,position summary art science seeking dynamic d...,[0.46185827]
5,1205,project coordinator san jose/evergreen communi...,[0.45047]
6,1454,office administrator global local total nation...,[0.45012635]
7,213,job code 403033 staff assistant iii duty & res...,[0.44600058]
8,335,administrative secretary position number 99383...,[0.44148213]
9,1394,Basic Qualifications :\n\nBachelor's degree in...,[0.43823946]