### View results of aggregate test

In [3]:
import pandas as pd
# import markdown
# from markdown import markdown

In [17]:
resume_df = pd.read_csv('../data/gpt_dataset.csv')
resume_df.iloc[34:]

,Category,Resume
34,Mobile App Developer (iOS/Android),Innovative Mobile App Developer with a focus o...
35,Mobile App Developer (iOS/Android),Passionate Mobile App Developer with a keen ey...
36,Mobile App Developer (iOS/Android),Dynamic Mobile App Developer with a passion fo...
37,Mobile App Developer (iOS/Android),Creative Mobile App Developer with a focus on ...
38,Mobile App Developer (iOS/Android),Experienced Mobile App Developer specializing ...
...,...,...
395,Cloud Engineer,Dynamic Cloud Engineer specializing in archite...
396,Cloud Engineer,Skilled Cloud Engineer with a focus on buildin...
397,Full Stack Developer,Experienced Full Stack Developer with expertis...
398,Full Stack Developer,Innovative Full Stack Developer with a passion...
399,Full Stack Developer,Dynamic Full Stack Developer specializing in b...

In [14]:
test_resume_id = resume_df[resume_df['Resume']==test_resume_instance].iloc[0,0]
test_resume_id

'Mobile App Developer (iOS/Android)'

In [36]:
#Change insert resume test id (csv name)
resume_id = 17422560
#fill here id above




df = pd.read_csv(f'all_tests_resumeid={resume_id}.csv')
resume_df = pd.read_csv('../data/Resume.csv')

In [37]:
#THE RESUME
r = resume_df[resume_df['ID']==resume_id]
print(r['Resume_html'].iloc[0])

<div class="fontsize fontface vmargins hmargins linespacing pagesize" id="document"> <div class="section firstsection" id="SECTION_NAME674977399" style="padding-top:0px;"> <div class="paragraph PARAGRAPH_NAME firstparagraph" id="PARAGRAPH_674977399_1_438702170" style="padding-top:0px;"> <div class="name thinbottomborder" itemprop="name"> <span class="field" id="674977399FNAM1"> </span> <span> </span> <span class="field" id="674977399LNAM1"> HR COORDINATOR</span> </div> <div class="myGap"> </div> <div class="lowerborder thinbottomborder"> </div> </div> </div> <div class="section" id="SECTION_SUMM674977417" style="padding-top:0px;"> <div class="heading"> <div class="sectiontitle thinbottomborder" id="SECTNAME_SUMM674977417"> Summary</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_674977417_1_438702181" style="padding-top:0px;"> <div class="field singlecolumn" id="674977417FRFM1"> To obtain a challenging career in the human resource field where I can utilize my capabilities and experiences to achieve goals as well as my personal development.</div> </div> </div> <div class="section" id="SECTION_HILT674977418" style="padding-top:0px;"> <div class="heading"> <div class="sectiontitle thinbottomborder" id="SECTNAME_HILT674977418"> Highlights</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_674977418_1_438702182" style="padding-top:0px;"> <div class="singlecolumn maincolumn"> <table class="twocol"> <tbody> <tr> <td class="field twocol_1 charspace" id="674977418SKC11"> <li> I have great knowledge of fax machines, printers, copiers, and computers.   I type about 45 wpm with a great accuracy I also have Microsoft Word, Excel Access and PowerPoint experience</li> </td> <td class="field twocol_2 charspace" id="674977418SKC21"> </td> </tr> </tbody> </table> </div> </div> </div> <div class="section" id="SECTION_ACCM674977880" style="padding-top:0px;"> </div> <div class="section" id="SECTION_EXPR674977401" style="padding-top:0px;"> <div class="heading"> <div class="sectiontitle thinbottomborder" id="SECTNAME_EXPR674977401"> Experience</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_674977401_1_438705355" itemscope="" itemtype="https://schema.org/Organization" style="padding-top:0px;"> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="674977401JTIT1"> HR Coordinator</span> <br/> <span> <span class="jobdates" format="%B %Y" id="674977401JSTD1"> February 2015</span> <span>  to </span> <span class="jobdates" format="%B %Y" id="674977401EDDT1"> Current</span> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="674977401COMP1" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="674977401JCIT1" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="674977401JSTA1" itemprop="addressRegion"> State</span> </span> <span class="paddedline"> <span class="jobline" id="674977401JDES1" itemprop="description"> <div> <span> <span> <span> Managed communication regarding employee orientation and open enrollment for benefits. </span> Offered consistent payroll disbursement with accurate record keeping of employee PTO and vacation accruals. </span> </span> </div> <div> <span> Explained human resources policies and procedures to all employees. <span> Conducted telephone and onsite exit interviews for all employees. <span> Answered employee questions during the entrance and exit interview processes. </span> </span> </span> </div> <div> <span> <span> <span> <span> Worked closely with HR business partners to facilitate year-end talent reviews and articulate team strengths. </span> </span> </span> </span> </div> <div> <span> <span> <span> <span> <span> Selected and interviewed candidates for all available positions. <span> Assessed employee performance and issued disciplinary notices. </span> </span> </span> </span> </span> </span> </div> <div> <span> <span> <span> <span> <span> <span> <span> Worked on 401(k) administration, FMLA and workers' compensation claims and benefits.</span> </span> </span> </span> </span> </span> </span> </div> <div> <span> <span> <span> <span> <span> <span> <span> <span> Managed over <font color="#000" style="color: rgb(0, 0, 0);"> 70</font>  personnel files according to policy and federal and state law and regulations.</span> </span> </span> </span> </span> </span> </span> </span> </div> <div> <span> <span> <span> <span> <span> <span> <span> <span> <span> Generated employee tracking reports each month. </span> </span> </span> </span> </span> </span> </span> </span> </span> </div> <div> <span> <span> <span> <span> <span> <span> <span> <span> <span> <span> Managed communication regarding employee orientation and open enrollment for benefits. </span> </span> </span> </span> </span> </span> </span> </span> </span> </span> </div> <div> <span> <span> <span> <span> <span> <span> <span> <span> <span> <span> <span> Organized employee schedules, department phone lists and business card orders. </span> </span> </span> </span> </span> </span> </span> </span> </span> </span> </span> </div> <div> <span> Ran queries and reports through the ADP system. </span> </div> <div> <span> Drafted department-specific employee announcements. </span> </div> <div> <span> Created social media initiatives for new employee search strategies.</span> </div> <div> <span> <span> Completed all work with a 95% rate of accuracy. </span> </span> </div> <div> <span> Resolved personnel issues regarding human resources matters needing clarification, submissions and corrections. </span> </div> <div> <span> Completed payroll processing from start to finish for more than <font color="#000" style="color: rgb(0, 0, 0);"> 65</font>  employees. </span> </div> <div> <span> ​</span> </div> <div> </div> <div> <span> <span> <span> <span> <span> <span> <span> <span> <span> ​</span> </span> </span> </span> </span> </span> </span> </span> </span> </div> </span> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_674977401_2_438702173" itemscope="" itemtype="https://schema.org/Organization" style="padding-top:0px;"> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="674977401JTIT2"> Payroll/Staffing Coordinator</span> <br/> <span> <span class="jobdates" format="%B %Y" id="674977401JSTD2"> June 2012</span> <span>  to </span> <span class="jobdates" format="%B %Y" id="674977401EDDT2"> Current</span> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="674977401COMP2" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="674977401JCIT2" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="674977401JSTA2" itemprop="addressRegion"> State</span> </span> <span class="paddedline"> <span class="jobline" id="674977401JDES2" itemprop="description"> <ul> <li> Maintains personal employment files Process payroll and set up E-time for employees Reconcile payroll journals and time cards Maintain and manage PTO balances Full On boarding function and recruiting duties Maintain OSHA logs and file workers compensation claims Employee relations liaison with client and supervisors Track and manage the credentials for an employee to maintain compliance Coordinate staffing needs to meet the organization's requirements Monitor overtime accumulation and attendance of employees Manage &amp; facilitate the orientation process Provide facility tours and tests to candidates and newly hired employees Conduct competency checks on new and existing employees.</li> </ul> </span> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_674977401_3_438702174" itemscope="" itemtype="https://schema.org/Organization" style="padding-top:0px;"> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="674977401JTIT3"> Tax Clerk/Secretary</span> <br/> <span> <span class="jobdates" format="%B %Y" id="674977401JSTD3"> August 2007</span> <span>  to </span> <span class="jobdates" format="%B %Y" id="674977401EDDT3"> June 2012</span> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="674977401COMP3" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="674977401JCIT3" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="674977401JSTA3" itemprop="addressRegion"> State</span> </span> <span class="paddedline"> <span class="jobline" id="674977401JDES3" itemprop="description"> <ul> <li> Creates control logs Files documents and maps in appropriate sequence and location Maintains personal production records and submits as required.</li> <li> Sets up informal review appointments for property owners Receptionist as needed  (answer phones, use of computers, copiers, printers, faxes, direct property owners in right direction, take messages, make appointment cards, and etc.) Utilizes multiple resources to determine correct mailing addresses when mail is returned from the Post Office.</li> <li> Data entry.</li> </ul> </span> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_674977401_4_438702175" itemscope="" itemtype="https://schema.org/Organization" style="padding-top:0px;"> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="674977401JTIT4"> General Appraisal/Data Entry Clerk</span> <br/> <span> <span class="jobdates" format="%B %Y" id="674977401JSTD4"> November 2006</span> <span>  to </span> <span class="jobdates" format="%B %Y" id="674977401EDDT4"> July 2007</span> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="674977401COMP4" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="674977401JCIT4" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="674977401JSTA4" itemprop="addressRegion"> State</span> </span> <span class="paddedline"> <span class="jobline" id="674977401JDES4" itemprop="description"> <ul> <li> Routing (associates field cards with appropriate maps in rational sequence for field work Files documents and maps in appropriate sequence and location Maintains personal production records and submits as required.</li> <li> Sets up informal review appointments for property owners Receptionist as needed  (answer phones, use of computers, copiers, printers, faxes, direct property owners in right direction, take messages, make appointment cards, and etc.) Utilizes multiple resources to determine correct mailing addresses when mail is returned from the Post Office.</li> </ul> </span> </span> </div> </div> <div class="paragraph" id="PARAGRAPH_674977401_5_438702176" itemscope="" itemtype="https://schema.org/Organization" style="padding-top:0px;"> <div class="singlecolumn"> <span class="paddedline"> <span class="jobtitle" id="674977401JTIT5"> Customer Service Rep</span> <br/> <span> <span class="jobdates" format="%B %Y" id="674977401JSTD5"> January 2005</span> <span>  to </span> <span class="jobdates" format="%B %Y" id="674977401EDDT5"> January 2006</span> </span> </span> <span class="paddedline" itemscope="" itemtype="https://schema.org/postalAddress"> <span class="companyname" id="674977401COMP5" itemprop="name"> Company Name</span> <span>  － </span> <span class="joblocation jobcity" id="674977401JCIT5" itemprop="addressLocality"> City</span> <span> , </span> <span class="joblocation jobstate" id="674977401JSTA5" itemprop="addressRegion"> State</span> </span> <span class="paddedline"> <span class="jobline" id="674977401JDES5" itemprop="description"> <ul> <li> Received cash from customers and employees in payment for goods and services, and recorded amounts received.</li> <li> Made change, cashed checks and issued receipts and tickets to customers.</li> <li> Recorded amounts received and prepared reports of transactions.</li> <li> Read and recorded totals shown on cash register tape and verified against cash on hand.</li> <li> Counted cash and reconciled charge sales and cash receipts with total sales to verify accuracy of transactions.</li> <li> Compiled reports, such as cash receipts, guest-bill charges and maintained high standards of excellence and sales.</li> <li> Provided information regarding activities and location of departments, offices and employees within organization Answer phones, use of computers, copiers, printers, faxes as needed.</li> </ul> </span> </span> </div> </div> </div> <div class="section" id="SECTION_EDUC674977409" style="padding-top:0px;"> <div class="heading"> <div class="sectiontitle thinbottomborder" id="SECTNAME_EDUC674977409"> Education</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_674977409_1_438702177" itemscope="" itemtype="https://schema.org/EducationalOrganization" style="padding-top:0px;"> <div class="singlecolumn"> <span class="paddedline" itemprop="description"> <span class="degree" dependency="DGRE" id="674977409DGRE1" itemprop="name"> AS</span> <span>  : </span> <span class="programline" dependency="STUY" id="674977409STUY1"> Business Management</span> <span> , </span> <span class="jobdates" id="674977409GRYR1"> Present</span> </span> <span class="paddedline"> <span class="companyname companyname_educ" dependency="SCHO" id="674977409SCHO1" itemprop="name"> Albany State Technical College</span> <span class="joblocation jobcity" id="674977409SCIT1"> </span> <span class="joblocation jobstate" id="674977409SSTA1"> </span> <span class="joblocation jobstate" id="674977409SCNT1"> </span> </span> <span class="paddedline"> <span class="field" id="674977409FRFM1"> Business Management</span> </span> </div> </div> </div> <div class="section" id="SECTION_SKLL674977419" style="padding-top:0px;"> <div class="heading"> <div class="sectiontitle thinbottomborder" id="SECTNAME_SKLL674977419"> Skills</div> </div> <div class="paragraph firstparagraph" id="PARAGRAPH_674977419_1_438702183" style="padding-top:0px;"> <div class="field singlecolumn" id="674977419FRFM1"> cash receipts, cash handling, cash register, client, customer service, Data entry, direction, Employee relations, faxes, fax machines, hiring, inventory, mailing, Access, Excel, mail, Office, PowerPoint, Microsoft Word, payroll, Process payroll, copiers, printers, Read, Receptionist, recruiting, Routing, sales, scheduling, staffing, take messages, answer phones, phone, type, 50 wpm</div> </div> </div> </div>

In [38]:
df.head(10)

,Unnamed: 0,tfidf_job_index,tfidf_job_descriptions,tfidf_scores,keyword_matching_job_index,keyword_matching_job_descriptions,keyword_matching_scores,encoder_job_index,encoder_job_descriptions,encoder_scores
0,0,2057,Company Description\nPositioned at Publicis Gr...,0.637576,0,We are looking for hire experts flutter develo...,5,1305,main responsibility hr administrator mainly ad...,[0.66506463]
1,1,509,"Responsible for design, development and implem...",0.631123,1521,Company Description\n\nGuestTek™ is a global l...,5,297,database coordinator ha overall responsibility...,[0.5870619]
2,2,1473,"Company Profile\nAt Morgan Stanley, we advise,...",0.627338,1515,JD for Software Engineer\nLocation-Hinjawadi P...,5,1454,office administrator global local total nation...,[0.5828285]
3,3,1401,Job Title\n\nSoftware Applications Developer I...,0.626191,1516,The project duration is 15 days\nBudget - 10k\...,5,1205,project coordinator san jose/evergreen communi...,[0.5520733]
4,4,1790,Software Developer - Web\n2200 S. Lakeside Dri...,0.624317,1517,Job Description*\nWe are looking for a PHP Dev...,5,2225,qualification required qualification high scho...,[0.53705984]

In [39]:
best_job_ids = df[['tfidf_job_index','keyword_matching_job_index','encoder_job_index']]
best_job_ids

   tfidf_job_index  keyword_matching_job_index  encoder_job_index
0             2057                           0               1305
1              509                        1521                297
2             1473                        1515               1454
3             1401                        1516               1205
4             1790                        1517               2225

In [40]:
#in both tfidf and encoder
[x for x in list(best_job_ids['tfidf_job_index']) if x in list(best_job_ids['encoder_job_index'])]

[]

In [41]:
tfidf = df.iloc[:,1:4]
tfidf

,tfidf_job_index,tfidf_job_descriptions,tfidf_scores
0,2057,Company Description\nPositioned at Publicis Gr...,0.637576
1,509,"Responsible for design, development and implem...",0.631123
2,1473,"Company Profile\nAt Morgan Stanley, we advise,...",0.627338
3,1401,Job Title\n\nSoftware Applications Developer I...,0.626191
4,1790,Software Developer - Web\n2200 S. Lakeside Dri...,0.624317

In [42]:
print(  tfidf.loc[1, 'tfidf_job_descriptions']   )

Responsible for design, development and implementation of network services and technologies to meet our client and enterprise requirements. Primary objective is to identify optimal networking and communications solutions that deliver long term capabilities, capacity, reliability and resiliency for the enterprise and clients to successfully maintain and grow business and client operations.
Duties and Responsibilities:
Lead (Preferably) level role that involves understanding client and enterprise technical requirements and designing and deploying optimal networking and connectivity solutions that enable clients and the enterprise to achieve their operational and business goals.
Required to prepare recommendations and supporting details for formal project proposals for network connectivity and configurations.
Day-to-day interaction with telecom providers, equipment suppliers and 3rd party network vendors, to engage their technical resources to perform tasks.
Role requires on-call support as well as scheduling and attendance for maintenance windows.
Resource can expect to routinely be called upon to analyze and interpret traffic and utilization of services on network connections.
Participation in disaster recovery exercises, pre-production certification testing and troubleshooting events is expected.
Coordinate internal operations to meet and exceed data communications project expectations (including but not limited to engineering/development, certifications testing, Network and IT Operations, capacity planning and production readiness.
Accountable for resolving all project level, cross-functional, partnership issues and escalations.
Manage client expectations for data communications connectivity and related services to Epsilon products and applications, throughout project(s) lifecycle. Client expectations include functionality, cost, delivery schedule, support readiness and relationships (usually working directly with senior level technical resources, project managers and business decision makers).
Qualifications
High organizational skills
Ability to handle multi-tasks and meet deadlines
Ability to work efficiently and productively with minimal direction or guidance
Capable of exercising extreme discretion and independent judgment
Ability to handle extremely confidential information in a professional manner
Ability to communicate, both verbally and written, with a high level of confidence
Travel < 20% of the year
MS Office skills with focus on Visio, Word and Excel
Education and Experience:
College degree or comparable certification in IT, telecommunications, computer science, or related field preferred.
Minimum seven years of experience required in design, planning, coordination and implementation of technology projects.
Must be experienced in the troubleshooting of complex multi-vendor geographically separated networks.
Experience in administrating authentication controls (Radius, RSA/SecureID and TACACS+) in the enterprise.
Experience with implementing and maintaining encryption techniques and standards (3DES, PKI, MD5, SSH, SSL), in a client and site-to-site configuration.
Must have operational level knowledge and experience in the deployment and maintenance of service provider network routing architectures using protocols such as OSPF, BGP, EIGRP, and RIP.
Expert knowledge in implementing and supporting switched networks, including (VTP, STP, HSRP, trunking, VLANs, port security and monitoring) in a multi-vendor environment.
Understanding of logical network design including: DMZs, WANs, and client connectivity solutions.
Requires an in-depth knowledge of TCP/IP and communication protocols in LAN / MAN / WAN environments.
Must be thoroughly proficient in the following protocols/technologies:
Route manipulation (Redistribution, Summarization, Route filtering and Policy Routing), VPN (client and site-to-site), Ethernet Switching: ( IOS, Junos switch configurations, VLANs/Trunking, Spanning Tree, HSRP/VRRP), IOS features: (PAT ,NAT, SNMP, Net Flow, QoS), Security server protocols (SCP, SFTP, HTTPS, etc.), Traffic filtering, Access lists, Radius, Tacacs+, IOS VPN, IPsec, Pix/ASA firewalls, Checkpoint firewalls, IDS/IPS, VPN Concentrators, Solarwinds Orion & NCM, Cisco Routers(ASR, 2900,3900, …), Catalyst 6500, 4500, Nexus, and other model switches, Citrix Netscaler and F5 load balancers/GTM, Infoblox DNS, Cisco Nexus & Juniper switches and routers.
Engineer should have knowledge on one of the cloud technologies either AWS, or Azure.
Automation scripting knowledge on tools like Phyton & Ansible is an added asset.
Engineer should have
This role requires strong communication skills.
This role requires strong project management skills.
This role also requires operational processes and technical foundations.
Preferred:
The following certifications are a plus: CCNA, CCNP, CCIE, ITIL Service Management.
Typical Physical Demands: Requires sitting, standing, bending, stooping, and reaching. May require some heavy lifting (75 pounds maximum) and carrying of up to 50 pounds at times. Requires manual dexterity sufficient to operate standard office machines such as computer, printer, copier, telephone and other office equipment. Requires normal range of hearing and vision.
Typical Mental Demands: Able to deal with stress associated with fast-paced work environment. Multiple priorities/tasks. Make judgment decisions and adapt to changing work situations. Grasp and apply new ideas. Communicate with various personalities at all levels.
Working Conditions: Works in a typical office setting but may be required to perform work in a data center. Occasionally called upon to work hours in excess of your normal daily schedule.
Conclusion: This position description is intended to convey information essential to understanding the scope of the position and it is not intended to be an exhaustive list of skills, efforts, duties, responsibilities or working conditions associated with this position.
Work Timings:
Engineer should be willing to work in 24*7*365 rotational shifts or static 04:30 AM IST – 01:30 PM IST shift (Monday and Friday) along with weekend on call support on rotational basis.

In [43]:
key_words = df.iloc[:,4:7]
key_words

,keyword_matching_job_index,keyword_matching_job_descriptions,keyword_matching_scores
0,0,We are looking for hire experts flutter develo...,5
1,1521,Company Description\n\nGuestTek™ is a global l...,5
2,1515,JD for Software Engineer\nLocation-Hinjawadi P...,5
3,1516,The project duration is 15 days\nBudget - 10k\...,5
4,1517,Job Description*\nWe are looking for a PHP Dev...,5

In [44]:
print(  key_words.loc[0, 'keyword_matching_job_descriptions']   )

We are looking for hire experts flutter developer. So you are eligible this post then apply your resume.
Job Types: Full-time, Part-time
Salary: ₹20,000.00 - ₹40,000.00 per month
Benefits:
Flexible schedule
Food allowance
Schedule:
Day shift
Supplemental Pay:
Joining bonus
Overtime pay
Experience:
total work: 1 year (Preferred)
Housing rent subsidy:
Yes
Industry:
Software Development
Work Remotely:
Temporarily due to COVID-19

In [45]:
encoder = df.iloc[:,7:10]
encoder

,encoder_job_index,encoder_job_descriptions,encoder_scores
0,1305,main responsibility hr administrator mainly ad...,[0.66506463]
1,297,database coordinator ha overall responsibility...,[0.5870619]
2,1454,office administrator global local total nation...,[0.5828285]
3,1205,project coordinator san jose/evergreen communi...,[0.5520733]
4,2225,qualification required qualification high scho...,[0.53705984]

In [46]:
print(  encoder.loc[5, 'encoder_job_descriptions']   )

KeyError: 5

In [47]:
print(  encoder.loc[5, 'encoder_job_descriptions']   )

KeyError: 5

In [20]:
pd.read_csv('../data/Resume.csv').shape

(2484, 4)

In [ ]:

job_df = pd.read_csv("../data/job_title_des.csv")
job_df.head(25)

,Unnamed: 0,Job Title,Job Description
0,0,Flutter Developer,We are looking for hire experts flutter develo...
1,1,Django Developer,PYTHON/DJANGO (Developer/Lead) - Job Code(PDJ ...
2,2,Machine Learning,"Data Scientist (Contractor)\n\nBangalore, IN\n..."
3,3,iOS Developer,JOB DESCRIPTION:\n\nStrong framework outside o...
4,4,Full Stack Developer,job responsibility full stack engineer – react...
5,5,Java Developer,Software Developer - Integration*\nImmediate O...
6,6,Full Stack Developer,senior full stack developer \- 1800026h cwt lo...
7,7,JavaScript Developer,"Job Description:\n\nReactJS + NodeJs, Azure Fu..."
8,8,DevOps Engineer,Main Responsibilities and Deliverables:\nManag...
9,9,Software Engineer,"Overview\n\n\nBased in Silicon Valley, Tintri ..."
10,10,Database Administrator,richardsontexasunited state bausp4 boeing comp...
11,11,Machine Learning,"Remote, Any where\n2 - 4 years\n₹8L - ₹12L / y..."
12,12,Machine Learning,"Excited by Big Data, Machine Learning and Pred..."
13,13,Software Engineer,As a member of our Software Engineering Group ...
14,14,Software Engineer,JOB DESCRIPTION\n\nJob Title: Software Enginee...
15,15,Java Developer,Overview:\n\nWestern National is seeking a hig...
16,16,Wordpress Developer,Experience: 2-5 years\n\nJob Location:- Aurang...
17,17,iOS Developer,Job Code : ID190704\n\nJob Description:\nExper...
18,18,Database Administrator,job description summary highly skilled technic...
19,20,DevOps Engineer,Job Summary\n\nOur mission at Style Theory is ...
20,21,Database Administrator,country place mortgage founded 1995 subsidiary...
21,22,Wordpress Developer,Position: WordPress Developer\nLocation: Prahl...
22,23,JavaScript Developer,MonetizeMore builds industry leading ad techno...
23,24,Database Administrator,qualification essential qualification related ...
24,25,PHP Developer,Job Summary\n**\nWe are looking for Fresher PH...